version: "3"

services:

  nginx:
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        - UID:82
        - GID:82
    ports:
    - 9000:80

  uwsgi:
    restart: always
    build:
      context: .
      dockerfile: docker/uwsgi/Dockerfile

  dht22:
    build:
      context: .
      dockerfile: docker/dht22/Dockerfile
    privileged: true
