version: "3"

services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
    - 9000:80

  uwsgi:
    build:
      context: .
      dockerfile: docker/uwsgi/Dockerfile
    ports:
      - 8080:8080

  dht22:
    build:
      context: .
      dockerfile: docker/dht22/Dockerfile
    privileged: true
