version: "3"

services:

  api:
    volumes:
      - ./api:/api
    environment:
      - FLASK_ENV=development
    command: uwsgi --socket 0.0.0.0:8060 --touch-reload /api/app/routes.py --wsgi-file /api/api.py

  db:
    volumes:
    - ./db:/db
    environment:
      - FLASK_ENV=development
    command: uwsgi --socket 0.0.0.0:8080 --touch-reload /db/app/routes.py --wsgi-file /db/db.py

  dht22:
    volumes:
      - ./dht22:/dht22
    environment:
      - FLASK_ENV=development
    command: uwsgi --socket 0.0.0.0:8090 --touch-reload /dht22/app/routes.py --wsgi-file /dht22/dht22.py

  web:
    volumes:
      - ./web/public:/usr/share/nginx/html

