version: "3"

services:

  api:
    restart: always
    build:
      context: .
      dockerfile: api/Dockerfile
    command: uwsgi --socket 0.0.0.0:8060 --wsgi-file /api/routes.py

  db:
    restart: always
    environment:
      - FLASK_ENV=production
    build:
      context: .
      dockerfile: db/Dockerfile
    command: uwsgi --socket 0.0.0.0:8080 --wsgi-file /db/db.py
    volumes:
    - db:/db/app.db

  dht22:
    restart: always
    build:
      context: .
      dockerfile: dht22/Dockerfile
    privileged: true
    command: uwsgi --http 0.0.0.0:8090 --wsgi-file /dht22/routes.py --logto /proc/self/fd/2

  proxy:
    restart: always
    build:
      context: .
      dockerfile: proxy/Dockerfile

  web:
    restart: always
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - 9000:80
    command: /wait-for api:8060 -- nginx -g 'daemon off;'

volumes:
  db:
