version: "3"

services:

  nginx:
    image: rdok/multimeter:nginx
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
    - 9000:80

  uwsgi:
    image: rdok/multimeter:uwsgi
    restart: always
    build:
      context: .
      dockerfile: docker/uwsgi/Dockerfile

  dht22:
    image: rdok/multimeter:dht22
    build:
      context: .
      dockerfile: docker/dht22/Dockerfile
    privileged: true
