version: "3"

services:

  db:
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile

  dht22:
    restart: always
    build:
      context: .
      dockerfile: dht22/Dockerfile
    privileged: true

  web:
    restart: always
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - 9000:80
