version: "3"

services:

  python3:
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#    - .:/app
    working_dir: /app
    privileged: true
    command: tail -f /dev/null
