version: "3"

services:

  db:
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    command: uwsgi --socket 0.0.0.0:8080 --wsgi-file /db/routes.py

  dht22:
    restart: always
    build:
      context: .
      dockerfile: dht22/Dockerfile
    privileged: true
    command: uwsgi --socket 0.0.0.0:8090 --wsgi-file /dht22/routes.py

  web:
    restart: always
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - 9000:80
    command: /wait-for db:8080 -- /wait-for dht22:8090 -- nginx -g 'daemon off;'
