#!/usr/bin/env php
<?php

require_once __DIR__ . '/config/bootstrap.php';

use App\Command\TemperatureCommand;
use Symfony\Component\Console\Application;

$application =  new Application();
$application->add(new TemperatureCommand);
$application->run();


